---
abstract: foo
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Mercurial
requires:
  File::Slurp: 0
  IPC::System::Simple: 0
  autodie: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-Mercurial
  repository: http://bitbucket.org/shlomif/perl-dist-zilla-plugin-mercurial
version: 0.02
